# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates approximate log-likelihood of simple stochastic volatility model (Taylor '82)
#'
#' @name svolApproxLL
#' @param y univariate time series vector
#' @param thetaProposal parameter vector (order is phi, beta, sigma)
#' @param uProposal standard normal variates of dimension time*(particles + 1) X 1
#' @return approximate log-likelihood
NULL

svolApproxLL <- function(y, thetaProposal, uProposal) {
    .Call('_pfexamplesinr_svolApproxLL', PACKAGE = 'pfexamplesinr', y, thetaProposal, uProposal)
}

